version: "3"
services:
    engecopi:
        image: tomcat:8-slim
        container_name: eng_engecopi
        ports:
            - "8026:8080"
        environment:
            TZ: "America/Fortaleza"
            EBEAN_PROPS: /etc/ebean.properties
        volumes:
            - ./build/libs/producao.war:/usr/local/tomcat/webapps/engEstoque.war
            - ./ebean.properties:/etc/ebean.properties
        restart: always
        networks:
            rede_eng:
                ipv4_address: 172.126.1.1
networks:
    rede_eng:
        ipam:
            driver: default
            config:
                - subnet: 172.126.0.0/16

