version: "3"
services:
    engecopi_app:
        image: tomcat:8
        container_name: eng_engecopi2
        ports:
            - "8081:8080"
        environment:
            TZ: "America/Fortaleza"
            EBEAN_PROPS: /etc/ebean.properties
        volumes:
            - ./build/libs/producao.war:/usr/local/tomcat/webapps/engEstoque.war
            - ./ebean.properties:/etc/ebean.properties
        restart: always
        networks:
            rede_eng2:
                ipv4_address: 172.181.1.1
networks:
    rede_eng2:
        ipam:
            driver: default
            config:
                - subnet: 172.181.0.0/16

