version: "3"
services:
    engecopi:
        image: tomcat:8
        container_name: eng_engecopi
        ports:
            - "8081:8080"
        environment:
            TZ: "America/Fortaleza"
            EBEAN_PROPS: /etc/ebean.properties
        volumes:
            - ./engEstoque.war:/usr/local/tomcat/webapps/engEstoque.war
            - ./logs:/usr/local/tomcat/logs
            - ./ebean.properties:/etc/ebean.properties
        restart: always
        networks:
            rede_eng:
                ipv4_address: 172.35.1.1
networks:
    rede_eng:
        ipam:
            driver: default
            config:
                - subnet: 172.35.0.0/16

